version: '3.4'

services:

  agent:
    container_name: docker-k3s-agent
    image: pjabadesco/docker-k3s:latest
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://server:6443
      - K3S_TOKEN=c840e8990d128792eaa9fa2e7727ea13c571a591347c631a88228b79b7ac1f52
    volumes:
      - k3s:/var/lib/rancher/k3s
      # - kubelet:/var/lib/kubelet
      # - cni:/var/lib/cni
      # - log:/var/log
    command: agent

volumes:
  k3s: null
  # kubelet: null
  # cni: null
  # log: null
